#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    rm -rf /var/lib/remsoundd
    if getent passwd remsoundd >/dev/null; then
        deluser --system remsoundd >/dev/null 2>&1 || true
    fi
    if getent group remsound >/dev/null; then
        delgroup --system remsound >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#
